version: '3.7'
services:
  django:
    build: .
    command: gunicorn WhatManager2.wsgi:application --bind 0.0.0.0:8000
    env_file: docker.env
    volumes:
      - './:/whatmanager'
    networks:
      - main
    depends_on:
      - db
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: docker.env
    environment: 
      - MYSQL_DATABASE=whatmanager
    volumes:
      - './media/mysql:/var/lib/mysql'
    networks:
      - main
  nginx:
    image: nginx
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/wm.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file: docker.env
    volumes:
      - './nginx.template:/etc/nginx/conf.d/wm.template:ro'
      - './static:/usr/share/nginx/whatmanager2/static'
    ports:
      - '80:80'
    networks:
      - main
    depends_on:
      - django
  rabbitmq:
    image: rabbitmq
    networks:
      - main
  trans_red:
    image: linuxserver/transmission
    env_file: docker.env
    environment: 
      - PGID=1000
      - PUID=1000
    networks:
      - main
    depends_on: 
      - django
      - db
    volumes:
      - './media/downloads:/whatmanager/media/downloads/'
      - './media/transmission/redacted01:/config'
    
networks:
  main: null
