# Generated by Django 3.0 on 2019-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181209_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupload',
            name='book_data',
            field=models.FileField(upload_to='temp/book_uploads'),
        ),
    ]
