# Generated by Django 3.0 on 2019-12-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181209_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatlogincache',
            name='cookies',
            field=models.BinaryField(),
        ),
    ]
