# Generated by Django 3.0 on 2019-12-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191212_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('PI', 'PTPIMG'), ('TI', 'Tidal'), ('QO', 'Qobuz')], max_length=2)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('session_id', models.CharField(blank=True, max_length=256, null=True)),
                ('preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='downloadlocation',
            name='preferred',
        ),
        migrations.RemoveField(
            model_name='downloadlocation',
            name='zone',
        ),
        migrations.AlterField(
            model_name='replicaset',
            name='zone',
            field=models.CharField(choices=[('redacted.ch', 'Redacted'), ('bibliotik.me', 'Bibliotik'), ('myanonamouse.net', 'MyAnonaMouse')], max_length=32),
        ),
        migrations.CreateModel(
            name='TrackerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('redacted.ch', 'Redacted'), ('bibliotik.me', 'Bibliotik'), ('myanonamouse.net', 'MyAnonaMouse')], max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('announce_url', models.URLField(blank=True, null=True)),
                ('snapshot_interval', models.IntegerField(default=600)),
                ('min_ratio', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('sync_files', models.BooleanField(default=False)),
                ('download_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DownloadLocation')),
            ],
        ),
    ]
